spring.application.name=regreportx
<<<<<<< HEAD
spring.datasource.url=jdbc:mysql://localhost:3306/bank17?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
=======
spring.datasource.url=jdbc:mysql://localhost:3306/bank1?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Niranj@97
>>>>>>> cbc6641281ccab5efc8889dd07c4810f4a9fd278
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=9090
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=4qhq8LrEBcYcaRHhx1TDmPQxyGWl24J1U+P6/WfW7OQ=
